vich_uploader:
    db_driver: orm

    mappings:
       descripFileM:
          uri_prefix: /admin/descriptifs/M
          upload_destination: '%kernel.project_dir%/public/admin/descriptifs/M/'

       descripFileL:
          uri_prefix: /admin/descriptifs/L
          upload_destination: '%kernel.project_dir%/public/admin/descriptifs/L'
